remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Chris Savage's git hub page]
tagline: [A place for all my projects for people to use.]
